# Generated by Django 5.0.6 on 2024-05-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
    ]
