# Generated by Django 5.0.6 on 2024-05-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_specialrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialrequest',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
