# Generated by Django 5.0.6 on 2024-06-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_specialrequest_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
