# Generated by Django 5.0.6 on 2024-05-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_category_options_menu_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Descrption',
            new_name='Description',
        ),
    ]
