# Generated by Django 5.0.6 on 2024-05-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='team/')),
                ('designation', models.CharField(max_length=50)),
                ('insta', models.URLField()),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'team',
            },
        ),
    ]
