# Generated by Django 5.0.6 on 2024-05-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('dateAndTime', models.DateTimeField()),
                ('no_of_people', models.IntegerField()),
                ('specialRequest', models.TextField()),
            ],
        ),
    ]
