# Generated by Django 5.0.6 on 2024-05-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='dateAndTime',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
