# Generated by Django 5.0.6 on 2024-05-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_dateandtime_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='specialRequest',
            field=models.TextField(null=True),
        ),
    ]
